[package]
name = "displayhub-player"
version = "0.3.1"
description = "DisplayHub Player for Windows and Linux"
authors = ["DisplayHub"]
edition = "2021"

[lib]
name = "displayhub_player_lib"
crate-type = ["staticlib","cdylib","rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
