import { useEffect, useState } from "react";
import { MonitorUp, Wifi, Settings, CheckCircle2, RefreshCw } from "lucide-react";

type Stage="setup"|"pairing"|"ready";
type PairRequest={code:string;requestToken:string;expiresIn:number};
type PairedScreen={id:number;name:string};
type Content={id:number;type:"image"|"video"|"pdf"|"text";title:string;text:string|null;imageUrl:string|null;mediaUrl:string|null};
type PlayerState={screen:{id:number;name:string;campus:string;organisationName:string;shortName:string;primary:string;secondary:string;accent:string;content:Content|null;playlist:{id:number;name:string;items:Array<Content&{durationSeconds:number}>}|null;layout:{id:number;name:string;backgroundColour:string;backgroundImageUrl:string|null;zones:Array<{key:string;type:string;positionX:number;positionY:number;positionWidth:number;positionHeight:number;zIndex:number;content:Content|null;playlist:{items:Array<Content&{durationSeconds:number}>}|null}>}|null;broadcast:{title:string;message:string;style:string}|null}};
const SERVER_KEY="displayhub_server_url";
const TOKEN_KEY="displayhub_device_token";
const SCREEN_KEY="displayhub_screen";

export default function App(){
 const [stage,setStage]=useState<Stage>("setup");
 const [serverUrl,setServerUrl]=useState(()=>localStorage.getItem(SERVER_KEY)||"http://localhost:8092");
 const[playerState,setPlayerState]=useState<PlayerState|null>(null);const[playIndex,setPlayIndex]=useState(0);const [pair,setPair]=useState<PairRequest|null>(null);const[screen,setScreen]=useState<PairedScreen|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{const token=localStorage.getItem(TOKEN_KEY),saved=localStorage.getItem(SCREEN_KEY);if(token&&saved){try{setScreen(JSON.parse(saved));setStage("ready")}catch{}}},[]);
 useEffect(()=>{if(stage!=="ready")return;const token=localStorage.getItem(TOKEN_KEY);if(!token)return;const refresh=async()=>{try{const r=await fetch(serverUrl+"/api/player/state",{headers:{authorization:"Bearer "+token,"x-displayhub-player-version":"0.3.0"}});if(r.status===401){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(SCREEN_KEY);setStage("setup");setPlayerState(null);return}if(r.ok)setPlayerState(await r.json())}catch{}};void refresh();const timer=window.setInterval(refresh,5000);return()=>window.clearInterval(timer)},[stage,serverUrl]);
 useEffect(()=>{const items=playerState?.screen.playlist?.items;if(!items?.length)return;const current=items[playIndex%items.length];const timer=window.setTimeout(()=>setPlayIndex(v=>(v+1)%items.length),(current.durationSeconds||10)*1000);return()=>window.clearTimeout(timer)},[playerState?.screen.playlist,playIndex]);
 async function beginPairing(){setBusy(true);setError("");try{const base=serverUrl.trim().replace(/\/$/,"");const r=await fetch(base+"/api/player/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deviceName:"DisplayHub Player",platform:navigator.platform||"desktop"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"DisplayHub did not accept the pairing request.");localStorage.setItem(SERVER_KEY,base);setServerUrl(base);setPair(d);setStage("pairing")}catch(e){setError(e instanceof Error?e.message:"Unable to reach DisplayHub. Check the server address and network.")}finally{setBusy(false)}}
 useEffect(()=>{if(stage!=="pairing"||!pair)return;let stopped=false;const check=async()=>{try{const r=await fetch(serverUrl+"/api/player/register/status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestToken:pair.requestToken})});const d=await r.json();if(stopped)return;if(d.status==="paired"){localStorage.setItem(TOKEN_KEY,d.token);localStorage.setItem(SCREEN_KEY,JSON.stringify(d.screen));setScreen(d.screen);setStage("ready")}else if(d.status==="expired"){setError("This pairing code expired. Request a new one.");setPair(null)}}catch{}};void check();const timer=window.setInterval(check,2000);return()=>{stopped=true;window.clearInterval(timer)}},[stage,pair,serverUrl]);
 const grouped=pair?pair.code.slice(0,3)+" "+pair.code.slice(3):"";
 return <main className="shell"><header className="topbar"><div className="brand"><span className="mark"><span/></span><strong>DisplayHub</strong><em>Player</em></div><div className="status"><Wifi size={16}/> Player 0.2.0</div></header><section className="content">
 {stage==="setup"&&<div className="card setup"><div className="heroIcon"><MonitorUp/></div><p className="eyebrow">Welcome to DisplayHub Player</p><h1>Turn this screen into a DisplayHub display.</h1><p className="lead">Connect this player to your DisplayHub server. It will create a code you can claim from your DisplayHub admin page.</p><label>DisplayHub server<input value={serverUrl} onChange={e=>setServerUrl(e.target.value)} placeholder="https://displayhub.example.com"/></label>{error&&<div className="appError">{error}</div>}<button onClick={beginPairing} disabled={busy||!serverUrl.trim()}>{busy?"Connecting…":"Connect to DisplayHub"}</button><small>You only need to do this once on each player.</small></div>}
 {stage==="pairing"&&<div className="card pairing"><p className="eyebrow">Pair this display</p><h1>Enter this code in DisplayHub</h1><div className="code">{grouped}</div><p className="lead">In your DisplayHub admin page, open <strong>Screens → Pair Player</strong> and enter the code above.</p>{error?<div className="appError">{error}</div>:<div className="waiting"><span className="pulse"/><span>Waiting for your DisplayHub administrator…</span></div>}<button className="secondary" onClick={beginPairing}><RefreshCw size={16}/> New pairing code</button><small>Pairing codes expire after 15 minutes.</small></div>}
 {stage==="ready"&&(playerState?<Signage state={playerState} serverUrl={serverUrl} index={playIndex}/>:<div className="card ready"><CheckCircle2 className="success"/><p className="eyebrow">Display connected</p><h1>{screen?.name||"DisplayHub Player"}</h1><p className="lead">Loading assigned signage…</p></div>)}
 </section><footer><span>DisplayHub Player</span><span><Settings size={14}/> Device setup</span></footer></main>
}
function Signage({state,serverUrl,index}:{state:PlayerState;serverUrl:string;index:number}){const s=state.screen;const url=(v:string|null)=>v?v.startsWith("http")?v:serverUrl+v:"";if(s.broadcast)return <div className="native-signage broadcast"><small>{s.shortName} · BROADCAST</small><h1>{s.broadcast.title}</h1><p>{s.broadcast.message}</p></div>;if(s.layout)return <div className="native-signage layout" style={{background:s.layout.backgroundColour,backgroundImage:s.layout.backgroundImageUrl?`url(${url(s.layout.backgroundImageUrl)})`:undefined}}>{s.layout.zones.map(z=><div className="native-zone" key={z.key} style={{left:z.positionX+"%",top:z.positionY+"%",width:z.positionWidth+"%",height:z.positionHeight+"%",zIndex:z.zIndex}}><Media content={z.playlist?.items?.[0]||z.content} url={url}/></div>)}</div>;const active=s.playlist?.items.length?s.playlist.items[index%s.playlist.items.length]:s.content;return <div className="native-signage"><Media content={active} url={url}/>{!active&&<div className="native-empty"><MonitorUp/><h1>{s.name}</h1><p>Ready for content</p></div>}</div>}
function Media({content,url}:{content:Content|null|undefined;url:(v:string|null)=>string}){if(!content)return <div className="native-empty">Waiting for content</div>;if(content.type==="image")return <img className="native-media" src={url(content.imageUrl)} alt={content.title}/>;if(content.type==="video")return <video className="native-media" src={url(content.mediaUrl)} autoPlay muted loop/>;if(content.type==="pdf")return <iframe className="native-media" src={url(content.mediaUrl)} title={content.title}/>;return <article className="native-text"><small>ANNOUNCEMENT</small><h1>{content.title}</h1><p>{content.text}</p></article>}
