import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { MonitorUp, Wifi, Settings, CheckCircle2, RefreshCw } from "lucide-react";

type Stage="setup"|"pairing"|"ready";
type PairRequest={code:string;requestToken:string;expiresIn:number};
type PairedScreen={id:number;name:string};
type Content={id:number;type:"image"|"video"|"pdf"|"text";title:string;text:string|null;imageUrl:string|null;mediaUrl:string|null};
type Zone={key:string;type:"content"|"playlist"|"clock"|"widget";imageFit:"cover"|"contain";textAlign:"left"|"center"|"right";widgetType:string|null;widgetConfig:Record<string,string>;widgetData:unknown;positionX:number;positionY:number;positionWidth:number;positionHeight:number;zIndex:number;content:Content|null;playlist:{id:number;name:string;items:Array<Content&{durationSeconds:number}>}|null};
type PlayerState={screen:{id:number;name:string;campus:string;organisationName:string;shortName:string;primary:string;secondary:string;accent:string;content:Content|null;playlist:{id:number;name:string;items:Array<Content&{durationSeconds:number}>}|null;layout:{id:number;name:string;showHeader:boolean;showFooter:boolean;freeform:boolean;backgroundColour:string;backgroundImageUrl:string|null;zoneGap:number;zones:Zone[]}|null;broadcast:{title:string;message:string;style:string}|null;airplayPinEnabled:boolean;airplayPin:string|null}};
const SERVER_KEY="displayhub_server_url";
const TOKEN_KEY="displayhub_device_token";
const SCREEN_KEY="displayhub_screen";
async function nativeRequest<T>(url:string,method="GET",body?:unknown,token?:string){return invoke<T>("http_request",{url,method,body:body??null,token:token??null})}

export default function App(){
 const [stage,setStage]=useState<Stage>("setup");
 const [serverUrl,setServerUrl]=useState(()=>localStorage.getItem(SERVER_KEY)||"http://localhost:8092");
 const[playerState,setPlayerState]=useState<PlayerState|null>(null);const[connectionLost,setConnectionLost]=useState(false);const[airplayReady,setAirplayReady]=useState(false);const[airplayCode,setAirplayCode]=useState<string|null>(null);const[airplayActive,setAirplayActive]=useState(false);const[airplayConfig,setAirplayConfig]=useState("");const[playIndex,setPlayIndex]=useState(0);const [pair,setPair]=useState<PairRequest|null>(null);const[screen,setScreen]=useState<PairedScreen|null>(null);const[deviceSettings,setDeviceSettings]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==="q"){e.preventDefault();void invoke("set_kiosk",{enabled:false})}else if(e.key==="F11"){e.preventDefault();void invoke("set_kiosk",{enabled:true})}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{const token=localStorage.getItem(TOKEN_KEY),saved=localStorage.getItem(SCREEN_KEY);if(token&&saved){try{setScreen(JSON.parse(saved));setStage("ready")}catch{}}},[]);
 useEffect(()=>{if(stage!=="ready")return;const token=localStorage.getItem(TOKEN_KEY);if(!token)return;const refresh=async()=>{try{const next=await nativeRequest<PlayerState>(serverUrl+"/api/player/state","GET",undefined,token);setPlayerState(next);setConnectionLost(false)}catch{setConnectionLost(true)}};void refresh();const timer=window.setInterval(refresh,5000);return()=>window.clearInterval(timer)},[stage,serverUrl]);
 useEffect(()=>{if(stage!=="ready"||!screen?.name)return;let cancelled=false;let starting=false;const dynamicCode=playerState?.screen.airplayPinEnabled??true;const startAirplay=async()=>{if(cancelled||starting)return;starting=true;try{await invoke("airplay_start",{name:screen.name,dynamicCode});await new Promise(r=>window.setTimeout(r,1200));const s=await invoke<{available:boolean;running:boolean;pin:string|null;active:boolean}>("airplay_status");if(!cancelled){setAirplayReady(s.available&&s.running);setAirplayCode(s.pin);setAirplayActive(s.active)}}catch{if(!cancelled)setAirplayReady(false)}finally{starting=false}};const check=async()=>{try{const s=await invoke<{available:boolean;running:boolean;pin:string|null;active:boolean}>("airplay_status");if(!cancelled){setAirplayReady(s.available&&s.running);setAirplayCode(s.pin);setAirplayActive(s.active)}if(!s.running)await startAirplay()}catch{if(!cancelled)setAirplayReady(false);await startAirplay()}};const initial=window.setTimeout(()=>void startAirplay(),3000);const timer=window.setInterval(()=>void check(),5000);return()=>{cancelled=true;window.clearTimeout(initial);window.clearInterval(timer)}},[stage,screen?.name,playerState?.screen.airplayPinEnabled]);

 useEffect(()=>{const items=playerState?.screen.playlist?.items;if(!items?.length)return;const current=items[playIndex%items.length];const timer=window.setTimeout(()=>setPlayIndex(v=>(v+1)%items.length),(current.durationSeconds||10)*1000);return()=>window.clearTimeout(timer)},[playerState?.screen.playlist,playIndex]);
 async function beginPairing(){setBusy(true);setError("");try{const base=serverUrl.trim().replace(/\/$/,"");const d=await nativeRequest<PairRequest>(base+"/api/player/register","POST",{deviceName:"DisplayHub Player",platform:navigator.platform||"desktop"});localStorage.setItem(SERVER_KEY,base);setServerUrl(base);setPair(d);setStage("pairing")}catch(e){setError(e instanceof Error?e.message:String(e||"Unable to reach DisplayHub. Check the server address and network."))}finally{setBusy(false)}}
 useEffect(()=>{if(stage!=="pairing"||!pair)return;let stopped=false;const check=async()=>{try{const d=await nativeRequest<{status:string;token?:string;screen?:PairedScreen}>(serverUrl+"/api/player/register/status","POST",{requestToken:pair.requestToken});if(stopped)return;if(d.status==="paired"){if(d.token&&d.screen){localStorage.setItem(TOKEN_KEY,d.token);localStorage.setItem(SCREEN_KEY,JSON.stringify(d.screen));setScreen(d.screen);}setStage("ready")}else if(d.status==="expired"){setError("This pairing code expired. Request a new one.");setPair(null)}}catch{}};void check();const timer=window.setInterval(check,2000);return()=>{stopped=true;window.clearInterval(timer)}},[stage,pair,serverUrl]);
 async function resetDevice(){if(!window.confirm("Reset this DisplayHub Player? It will forget its current screen and return to pairing."))return;try{await invoke("airplay_stop")}catch{}localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(SCREEN_KEY);setPlayerState(null);setScreen(null);setPair(null);setAirplayReady(false);setAirplayCode(null);setAirplayActive(false);setConnectionLost(false);setDeviceSettings(false);setStage("setup")}
 const grouped=pair?pair.code.slice(0,3)+" "+pair.code.slice(3):"";
 return <main className="shell"><header className="topbar"><div className="brand"><span className="mark"><span/></span><strong>DisplayHub</strong><em>Player</em></div><div className="status"><Wifi size={16}/> Player 0.3.2</div></header><section className="content">
 {stage==="setup"&&<div className="card setup"><div className="heroIcon"><MonitorUp/></div><p className="eyebrow">Welcome to DisplayHub Player</p><h1>Turn this screen into a DisplayHub display.</h1><p className="lead">Connect this player to your DisplayHub server. It will create a code you can claim from your DisplayHub admin page.</p><label>DisplayHub server<input value={serverUrl} onChange={e=>setServerUrl(e.target.value)} placeholder="https://displayhub.example.com"/></label>{error&&<div className="appError">{error}</div>}<button onClick={beginPairing} disabled={busy||!serverUrl.trim()}>{busy?"Connecting…":"Connect to DisplayHub"}</button><small>You only need to do this once on each player.</small></div>}
 {stage==="pairing"&&<div className="card pairing"><p className="eyebrow">Pair this display</p><h1>Enter this code in DisplayHub</h1><div className="code">{grouped}</div><p className="lead">In your DisplayHub admin page, open <strong>Screens → Pair Player</strong> and enter the code above.</p>{error?<div className="appError">{error}</div>:<div className="waiting"><span className="pulse"/><span>Waiting for your DisplayHub administrator…</span></div>}<button className="secondary" onClick={beginPairing}><RefreshCw size={16}/> New pairing code</button><small>Pairing codes expire after 15 minutes.</small></div>}
 {stage==="ready"&&(playerState?<><Signage state={playerState} serverUrl={serverUrl} index={playIndex}/>{connectionLost&&<div className="connection-warning">DisplayHub offline · reconnecting…</div>}{airplayReady&&!airplayActive&&<div className="airplay-ready" title={`AirPlay: DisplayHub – ${screen?.name}`}>AirPlay ready</div>}{airplayCode&&!airplayActive&&<div style={{position:"fixed",inset:0,zIndex:99999,display:"grid",placeItems:"center",background:"rgba(9,14,28,.88)",backdropFilter:"blur(18px)",color:"white"}}><div style={{textAlign:"center",padding:"48px 64px",borderRadius:32,background:"rgba(255,255,255,.1)",border:"1px solid rgba(255,255,255,.18)",boxShadow:"0 24px 80px rgba(0,0,0,.35)"}}><p style={{fontSize:18,letterSpacing:2,textTransform:"uppercase",opacity:.7,margin:"0 0 14px"}}>AirPlay</p><h1 style={{fontSize:44,margin:"0 0 14px"}}>Enter this code to present</h1><div style={{fontSize:104,fontWeight:800,letterSpacing:24,lineHeight:1.15,marginLeft:24}}>{airplayCode}</div><p style={{fontSize:20,opacity:.72,margin:"20px 0 0"}}>DisplayHub – {screen?.name}</p></div></div>}</>:<div className="card ready"><CheckCircle2 className="success"/><p className="eyebrow">Display connected</p><h1>{screen?.name||"DisplayHub Player"}</h1><p className="lead">Loading assigned signage…</p></div>)}
 </section>{deviceSettings&&<div style={{position:"fixed",inset:0,zIndex:100000,display:"grid",placeItems:"center",background:"rgba(9,14,28,.72)",backdropFilter:"blur(14px)"}} onClick={()=>setDeviceSettings(false)}><div onClick={e=>e.stopPropagation()} style={{width:"min(520px,calc(100vw - 32px))",background:"#fff",color:"#151b2d",borderRadius:24,padding:28,boxShadow:"0 24px 80px rgba(0,0,0,.35)"}}><p className="eyebrow">DEVICE SETTINGS</p><h2 style={{margin:"6px 0 6px"}}>{screen?.name||"DisplayHub Player"}</h2><p style={{margin:"0 0 22px",opacity:.65}}>Manage this physical player and its DisplayHub connection.</p><div style={{display:"grid",gap:10,marginBottom:22}}><div style={{padding:14,borderRadius:14,background:"#f4f6fa"}}><small style={{opacity:.6}}>LINKED SCREEN</small><strong style={{display:"block",marginTop:4}}>{screen?.name||"Not linked"}</strong></div><div style={{padding:14,borderRadius:14,background:"#f4f6fa"}}><small style={{opacity:.6}}>DISPLAYHUB SERVER</small><strong style={{display:"block",marginTop:4,overflowWrap:"anywhere"}}>{serverUrl}</strong></div><div style={{padding:14,borderRadius:14,background:"#f4f6fa"}}><small style={{opacity:.6}}>CONNECTION</small><strong style={{display:"block",marginTop:4}}>{stage==="ready"?(connectionLost?"Offline · reconnecting":"Connected"):"Not paired"}</strong></div></div><div style={{display:"flex",gap:10,justifyContent:"flex-end",flexWrap:"wrap"}}><button className="secondary" onClick={()=>setDeviceSettings(false)}>Close</button><button onClick={()=>void resetDevice()} style={{background:"#b94b47"}}>Reset &amp; re-pair device</button></div><p style={{fontSize:12,opacity:.55,margin:"16px 0 0"}}>Resetting only forgets the link on this player. The old screen record can still be removed from DisplayHub admin.</p></div></div>}<footer><span>DisplayHub Player</span><button type="button" onClick={()=>setDeviceSettings(true)} style={{border:0,background:"transparent",color:"inherit",display:"inline-flex",alignItems:"center",gap:6,cursor:"pointer"}}><Settings size={14}/> Device settings</button></footer></main>
}
function Signage({state,serverUrl,index}:{state:PlayerState;serverUrl:string;index:number}){const s=state.screen;const url=(v:string|null)=>v?v.startsWith("http")?v:serverUrl+v:"";if(s.broadcast)return <div className="native-signage broadcast"><small>{s.shortName} · BROADCAST</small><h1>{s.broadcast.title}</h1><p>{s.broadcast.message}</p></div>;if(s.layout)return <LayoutSignage layout={s.layout} serverUrl={serverUrl}/>;const active=s.playlist?.items.length?s.playlist.items[index%s.playlist.items.length]:s.content;return <div className="native-signage"><Media content={active} url={url}/>{!active&&<div className="native-empty"><MonitorUp/><h1>{s.name}</h1><p>Ready for content</p></div>}</div>}
function LayoutSignage({layout,serverUrl}:{layout:NonNullable<PlayerState["screen"]["layout"]>;serverUrl:string}){const url=(v:string|null)=>v?v.startsWith("http")?v:serverUrl+v:"";return <div className="native-layout" style={{backgroundColor:layout.backgroundColour||"#11172a",backgroundImage:layout.backgroundImageUrl?`linear-gradient(#1114,#1114),url(${url(layout.backgroundImageUrl)})`:undefined}}>{layout.showHeader&&<header className="native-layout-header"><strong>DisplayHub</strong><time>{new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></header>}<div className="native-layout-canvas" style={{top:layout.showHeader?"7%":"0",bottom:layout.showFooter?"5%":"0"}}>{layout.zones.map(zone=><div className="native-zone" key={zone.key} style={{left:zone.positionX+"%",top:zone.positionY+"%",width:zone.positionWidth+"%",height:zone.positionHeight+"%",zIndex:zone.zIndex,padding:(layout.zoneGap||0)/2}}><ZoneMedia zone={zone} url={url}/></div>)}</div>{layout.showFooter&&<footer className="native-layout-footer"><span>{layout.name}</span><span>DisplayHub</span></footer>}</div>}
function ZoneMedia({zone,url}:{zone:Zone;url:(v:string|null)=>string}){const[index,setIndex]=useState(0);const items=zone.playlist?.items;useEffect(()=>{setIndex(0)},[zone.playlist?.id]);useEffect(()=>{if(!items?.length)return;const current=items[index%items.length];const timer=window.setTimeout(()=>setIndex(v=>(v+1)%items.length),(current.durationSeconds||10)*1000);return()=>window.clearTimeout(timer)},[index,items]);if(zone.type==="widget"||zone.type==="clock")return <Widget zone={zone}/>;const content=items?.length?items[index%items.length]:zone.content;if(!content)return null;return <Media content={content} url={url} fit={zone.imageFit} align={zone.textAlign}/>}
function Widget({zone}:{zone:Zone}){const c=zone.widgetConfig||{};const data=(zone as Zone&{widgetData?:any}).widgetData;if(zone.widgetType==="clock"||zone.type==="clock")return <div className="native-clock"><small>{new Date().toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"})}</small><strong>{new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</strong></div>;if(zone.widgetType==="info")return <article className="native-widget native-info"><small>INFORMATION</small><strong>{c.title||"Information"}</strong><p>{c.text}</p></article>;if(zone.widgetType==="countdown"){const d=Math.max(0,new Date(c.targetAt||"").getTime()-Date.now()),days=Math.floor(d/86400000),hours=Math.floor(d%86400000/3600000),mins=Math.floor(d%3600000/60000);return <article className="native-widget"><small>{c.title||"Upcoming event"}</small><strong>{d?`${days}d ${hours}h ${mins}m`:"Event started"}</strong></article>}if(zone.widgetType==="ticker")return <article className="native-widget"><small>{c.title||"Latest"}</small><strong>{c.text||"School update"}</strong></article>;if(zone.widgetType==="menu"||zone.widgetType==="timetable")return <article className="native-widget native-feed"><small>{zone.widgetType==="menu"?"MENU":"TIMETABLE"}</small><strong>{c.title||(zone.widgetType==="menu"?"Today’s menu":"Today’s timetable")}</strong>{(c.items||"").split("\n").filter(Boolean).slice(0,8).map((item:string,i:number)=><p key={i}>• {item}</p>)}</article>;if(zone.widgetType==="rss"||zone.widgetType==="calendar"){const items=Array.isArray(data?.items)?data.items:[];return <article className="native-widget native-feed"><small>{zone.widgetType==="rss"?"LATEST NEWS":"UPCOMING"}</small><strong>{c.title||(zone.widgetType==="rss"?"Latest news":"Upcoming events")}</strong>{items.slice(0,5).map((item:any,i:number)=><p key={i}>• {item.title||item.summary||String(item)}</p>)}</article>}if(zone.widgetType==="weather")return <article className="native-widget"><small>WEATHER</small><strong>{data?.temperature??data?.temp??"—"}{data?.temperature||data?.temp?"°":""}</strong><p>{c.location||""}</p></article>;return <article className="native-widget"><strong>{c.title||"DisplayHub"}</strong><p>{c.text||""}</p></article>}
function Media({content,url,fit="contain",align="center"}:{content:Content|null|undefined;url:(v:string|null)=>string;fit?:"cover"|"contain";align?:"left"|"center"|"right"}){if(!content)return null;if(content.type==="image")return <img className="native-media" style={{objectFit:fit}} src={url(content.imageUrl)} alt={content.title}/>;if(content.type==="video")return <video className="native-media" style={{objectFit:fit}} src={url(content.mediaUrl)} autoPlay muted loop/>;if(content.type==="pdf")return <iframe className="native-media" src={url(content.mediaUrl)+"#toolbar=0&navpanes=0&view=FitH"} title={content.title}/>;return <article className="native-text" style={{textAlign:align}}><small>ANNOUNCEMENT</small><h1>{content.title}</h1><p>{content.text}</p></article>}
